packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  hono: ^4.6.20
  tailwind-merge: ^3.0.1
  tw-animate-css: ^1.2.4
  tailwindcss: ^4.0.8
  eslint: ^9.20.0
  autoprefixer: ^10.4.20
  "@tailwindcss/postcss": ^4.0.8
  prettier: ^3.4.2
  typescript: ^5.6.3
  "@types/node": ^20
  "zod": ^3.24.1

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
