/// <reference path="sst-env.d.ts" />

import "sst";

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "langdb-api-key": {
      type: "sst.sst.Secret";
      value: string;
    };
    "langdb-openai-base-url": {
      type: "sst.sst.Secret";
      value: string;
    };
    "langdb-project-id": {
      type: "sst.sst.Secret";
      value: string;
    };
    "plobbo-bucket": {
      name: string;
      type: "sst.aws.Bucket";
    };
    "plobbo-pg": {
      database: string;
      host: string;
      password: string;
      port: number;
      type: "sst.aws.Postgres";
      username: string;
    };
    "plobbo-ses": {
      configSet: string;
      sender: string;
      type: "sst.aws.Email";
    };
    "plobbo-vpc": {
      type: "sst.aws.Vpc";
    };
    "plobbo-www": {
      type: "sst.aws.Nextjs";
      url: string;
    };
  }
}

export {};
