/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "CLOUDFLARE_R2_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "dashboard": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "www": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "d1": cloudflare.D1Database
    "kv": cloudflare.KVNamespace
    "r2": cloudflare.R2Bucket
  }
}

import "sst"
export {}